### ISSUE TITLE
DbExtract doesn't support Revision update type

### ISSUE THREAD

**Issue by nixnut** [RobWunderlich/Qlikview-Components#40] opened 2016-03-11 11:43 UTC
The DbExtract routine is missing a few bits to support update type Revision:

LET _qvctemp.den.updateFieldType = peek('UpdateFieldType', $(_qvctemp.den._listIndex), '$(_qvctemp.den.extractList)');

IF len('$(_qvctemp.den.updateFieldType)') > 0 THEN 
	SET Qvc.Loader.v.ModField.Type = $(_qvctemp.den.updateFieldType);
ENDIF

**Comment by RobWunderlich** [comment] 2016-07-29 00:08
Duplicate of #47

**Closed by RobWunderlich** 2016-07-29 00:08 UTC
